changelog:
  categories:
    - title: New features
      labels:
        - feature
    - title: Fixes
      labels:
        - fix
    - title: Dependencies
      labels:
        - dependency
    - title: Other changes
      labels:
        - '*'
